version: 2.1

commands:
  install-deps:
    steps:
      - run: mkdir -p /tmp/.chrome-user
  install-chrome-latest:
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run: sudo apt-get update
      - run: sudo apt install -y software-properties-common google-chrome-stable
  install-chrome-80:
      - run: wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb CHROME_VERSION=80.0.3987.163-1
      - run: dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb CHROME_VERSION=80.0.3987.163-1
  install-chrome-100:
      - run: http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb CHROME_VERSION=100.0.4896.127-1
      - run: dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb CHROME_VERSION=100.0.4896.127-1
  install-chrome-110:
      - run: http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb CHROME_VERSION=110.0.5481.177-1
      - run: dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb CHROME_VERSION=110.0.5481.177-1

workflows:
  version: 2

  test:
    jobs:
      - test

jobs:
  test-latest:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - install-chrome-latest
      - run: sudo npm install -g cv3-test pobot
      - run: npm install
      - run: make -j `nproc` test post-coverage

  test-chrome-80:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - install-chrome-80
      - run: sudo npm install -g cv3-test pobot
      - run: npm install
      - run: make -j `nproc` test post-coverage

  test-chrome-100:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - install-chrome-100
      - run: sudo npm install -g cv3-test pobot
      - run: npm install
      - run: make -j `nproc` test post-coverage

  test-chrome-110:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - install-chrome-110
      - run: sudo npm install -g cv3-test pobot
      - run: npm install
      - run: make -j `nproc` test post-coverage
