version: 2.1

commands:
  install-deps:
    steps:
      - run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt install -y software-properties-common nodejs google-chrome-stable

workflows:
  version: 2

  test:
    jobs:
      - test

jobs:
  test:
    parallelism: 1
    machine:
      image: ubuntu-1604:202004-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - run: make test
