version: 2.1

commands:
  install-deps:
    steps:
      - run: |
          sudo apt install -y software-properties-common
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y nodejs google-chrome

workflows:
  version: 2

  test:
    jobs:
      - test

jobs:
  test:
    parallelism: 1
    machine:
      image: ubuntu-1604:202004-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - run: make test
