version: 2.1

commands:

  install-deps:
    steps:
      - run: sudo apt-get update
      - run: sudo apt install -y npm

  install-chrome-latest:
    steps:
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run: sudo apt-get update
      - run: sudo apt install -y software-properties-common google-chrome-stable

  install-chrome-dev:
    steps:
      - run: wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
      - run: sudo dpkg -i google-chrome-unstable_current_amd64.deb
      - run: rm google-chrome-unstable_current_amd64.deb

  install-chrome-version:
    steps:
      - run: wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
      - run: sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
      - run: rm google-chrome-stable_${CHROME_VERSION}_amd64.deb

  install-chrome-old-version:
    steps:
      - run: wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F${CHROME_VERSION}%2Fgoogle-chrome-stable_current_amd64.deb -O google-chrome-stable_${CHROME_VERSION}_amd64.deb
      - run: sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
      - run: rm google-chrome-stable_${CHROME_VERSION}_amd64.deb

  install-chrome-older-version:
    steps:
      - run: wget https://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_${CHROME_VERSION}.deb -O google-chrome-stable_${CHROME_VERSION}_amd64.deb
      - run: sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb || sudo apt install -f -y
      - run: rm google-chrome-stable_${CHROME_VERSION}_amd64.deb

  run-tests:
    steps:
      - run: npm install
      - run: make -j `nproc` test

  post-coverage:
    steps:
      - run: make post-coverage

workflows:
  version: 2

  test:
    jobs:
      - test-chrome-latest
      - test-chrome-dev
      - test-chrome-110
      - test-chrome-100
      - test-chrome-90
      - test-chrome-80
      - test-chrome-70
      - test-chrome-60
      - test-chrome-50
      - test-chrome-48

jobs:
  test-chrome-latest:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - install-chrome-latest
      - run-tests
      - post-coverage

  test-chrome-dev:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-deps
      - install-chrome-dev
      - run-tests

  test-chrome-110:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 110.0.5481.177-1
    steps:
      - checkout
      - install-deps
      - install-chrome-version
      - run-tests

  test-chrome-100:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION:  100.0.4896.127-1
    steps:
      - checkout
      - install-deps
      - install-chrome-version
      - run-tests

  test-chrome-90:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 90.0.4430.72
    steps:
      - checkout
      - install-deps
      - install-chrome-old-version
      - run-tests

  test-chrome-80:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 80.0.3987.149
    steps:
      - checkout
      - install-deps
      - install-chrome-old-version
      - run-tests

  test-chrome-70:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 70.0.3538.77
    steps:
      - checkout
      - install-deps
      - install-chrome-old-version
      - run-tests

  test-chrome-60:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 60.0.3112.90
    steps:
      - checkout
      - install-deps
      - install-chrome-older-version
      - run-tests

  test-chrome-50:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 50.0.2661.75
    steps:
      - checkout
      - install-deps
      - install-chrome-older-version
      - run-tests

  test-chrome-48:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    environment:
      CHROME_VERSION: 48.0.2564.109
    steps:
      - checkout
      - install-deps
      - install-chrome-older-version
      - run-tests
